config/routes.rb
Blogger::Application.routes.draw do
	root to: "articles#index"

resources :articles do 
	resources :comments
end 
resources :tags
resources :authors
resources :auths
#get "auths/new" => "auths#new", :as => :new_auth 
end 

app/models/article.rb
class Article < ActiveRecord::Base

	include Mongoid::Document
	include Mongoid::Paperclip

	field :title, type: String
	field :body, type: String 
	# has_mongoid_attached_file :image
	has_many :comments
	has_many :taggings
	# validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	def self.after_commit(*args, &block)
    args.each do |arg|
    case arg[:on]
      when :destroy
        after_destroy &block
      end
    end
  end


def tag_list 
self.tags.collect do |tag| 
	tag.name 
end.join(",")
end



def tag_list=(tags_string)
  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  self.tags = new_or_found_tags
end


end

app/models/author.rb
require "bcrypt"

class Author < ActiveRecord::Base

	include Mongoid::Document

	field :email, type: String
	field :hashed_password, type: String 
	field :salt, type: String



	attr_accessor :password 
						#pwd represents the actual password someone is passing in from the
						#auths controller 
						#question marks in Ruby basically asks if something is true/false
						#pwd acts as a parameter
	def authenticated? pwd 
		self.hashed_password == BCrypt::Engine.hash_secret(pwd, self.salt)

	end 	 




	before_save :hash_stuff 	

	private 
		def hash_stuff 
			self.salt = BCrypt::Engine.generate_salt 
			self.hashed_password = BCrypt::Engine.hash_secret(self.password, self.salt)
			self.password = nil

		end 

	
   


end


		#Anything above private is the public interface
		#self.salt creates a 20 character string of random shit. 
		#self.hashed_password takes the password and salt, adds them
		#together and randomizes them again
		#self.password instead of saving passwords to the database, it clear it out
		#every single time it tries to create/save a user it's gonna do stuff above

app/models/comment.rb
class Comment < ActiveRecord::Base
	include Mongoid::Document


	field :author_name, type: String
	field :body, type: String 
	field :article_id, type: Integer 





  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	include Mongoid::Document
	
    field :name, type: String
    field :created_at, type: Datetime 
    field :updated_at, type: Datetime

	has_many :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
	include Mongoid::Document	
	field :tag_id, type: Integer 
	field :article_id, type: Integer 

  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user 
  #if it someone is logged in then find them by their session id 
  def current_user 
  	if session[:author_id]
  		Author.find_by(id: session[:author_id])
  	end 

  end 


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
include ArticlesHelper

def index 
	@articles = Article.all 
end 

def update 
	@article = article.find(params[:id])
	@article.update(article_params)
	flash.notice = "Article" '#{article.title} Updated!'

	redirect_to article_path(@article)
end 

def destroy 
	@article = Article.find(params[:id])
	@article.destroy 
	redirect_to articles_path
end 

def show 
	@article = Article.find(params[:id])
	@comment = Comment.new
	@comment.article_id = @article.id

end 

def edit 
	@article = Article.find(params[:id])
end 

def new 
	@article = Article.new 
end 

def create 
@article = Article.new(article_params) 
@article.save 
redirect_to article_path(@article)

end 

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	def index 
		@authors = Author.all 
	end 

	def new 
		@author = Author.new
		
	end 


	def create 
		@author = Author.new(params.require(:author).permit(:email, :password))
		if @author.save
				redirect_to articles_path 
		else 
			render action: "index"
		end 



	end 

	def show 
		@author = Author.find(params[:id])
	end 









end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
	def new  
		if current_user 
			redirect_to articles_path 
		else 
			@author = Author.new 

		end 
 	end 

	def create 
		#if they're authenticated, then create a session equal to the id of 
		#that particular author in the database  
		author = Author.find_by(email: params[:author][:email])
		if author.authenticated?(params[:author][:password])
			session[:author_id]=author.id 
			redirect_to articles_path
		else 
			render action: "new"

		end 
	end 


	def destroy 
		session[:author_id] = nil
		redirect_to new_auth_path



	end 	









end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create 
	@comment = Comment.new(comment_params)
	@comment.article_id = params[:article_id]

	@comment.save

	redirect_to article_path(@comment.article)
end 

def index 
	@comments = Comment.all
end 

def comment_params 
	params.require(:comment).permit(:author_name, :body)

end 




end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

def show 
	@tag = Tag.find(params[:id])
end


def index 
	@tags = Tag.all
end 




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
	    params.require(:article).permit(:title, :body, :tag_list, :image)
	end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
  <%= form_for(@article, html: {multipart: true}) do |f| %>
    <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
      </ul>

    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>

   
    <p>
      <%= f.submit %>
    </p>







  <% end %>

app/views/articles/index.html.erb
<h1>All Articles </h1>

<ul id = "articles"> 

<% @articles.each do |art| %> 
	<li>
	<%= link_to art.title, article_path(art) %>
	</li>
<%end%>

<%= link_to "New Article", new_article_path, class: "new_article" %>


<%=link_to "New Author", new_author_path %> 

<%=link_to "Sign In", new_auth_path %> 

<%#=link_to "Sign Out", {:controller => "auths", :action => "destroy"}, {:method => :delete} %> 


</ul> 

app/views/articles/new.html.erb
<h1>Create a new Article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
	<h1><%=@article.title %></h1>

	


	<p><%= @article.body %></p>






	<%= render partial: 'comments/form' %>
	<h3>Comments</h3>
	<%= render partial: 'comment', collection: @article.comments %>
	<%= link_to "<< Back to Articles list", articles_path %>
	<%= link_to "delete",  {:action => 'destroy'}, :method => :delete, data: {confirm: "Oh no you're gonna delete are you sure?"}  %>

	<h3>Comments <%= @article.comments.size %> </h3>

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email, :placeholder => "enter email" %>
  </p>

   <p>
    <%= f.label :password %><br/>
    <%= f.text_field :password, :placeholder => "enter password" %>
  </p>
  
  
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/authors/index.html.erb
index.html.erb

app/views/authors/new.html.erb
<h3>Create a new author </h3>

<%= render partial: "form" %> 

app/views/auths/new.html.erb
<%= form_for @author, {url: "/auths"} do |f| %>
  <p> 
    <%= f.label :email %> <br/>
    <%= f.text_field :email, :placeholder => "enter email" %>
 </p> 


<p>
    <%= f.label :password %><br/>
    <%= f.text_field :password, :placeholder => "enter password" %>
</p>
  
 
    <%= f.submit 'Log In' %>
  

<% end %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag  "application" %> 
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash"><%= flash.notice %></p> 
<%= yield %>

</body>
</html>

app/views/tags/index.html.erb
<h1>All tags </h1>

<ul id = "tags"> 

<% @tags.each do |t| %> 
	<li>
	<%= link_to "Back", article_path(t) %>
	</li>
<%end%>

</ul>

app/views/tags/show.html.erb
<h1>
Articles Tagged with <%= @tag.name %> 
</h1>

<ul>

<% @tag.articles.each do |article| %> 

<li> 
<%= link_to "Back", article_path(article) %> 
<%end%> 


</li> 

</ul>